SELECT * FROM MESSY_SALES_DATASET;

--------------------------------------------------------------------------------------------
-- CLEANING RAW DATA
---------------------------------------------------------------------------------------------

-- 1 STANDARDIZE CITY

SELECT CITY ,
CASE
WHEN LOWER(CITY) LIKE '%new york%' THEN 'New York'
WHEN LOWER(CITY) LIKE '%los angeles%' THEN 'Los Angeles'
WHEN LOWER(CITY) LIKE '%chicago%' THEN 'Chicago'
ELSE 'Other'
END AS FORMATTED_CITY
FROM MESSY_SALES_DATASET;

-- 2 STANDARDIZE ITEM

SELECT ITEM ,
CASE 
WHEN  LOWER(ITEM) LIKE '%laptop%' THEN 'Laptop'
WHEN LOWER(ITEM) LIKE '%tablet%'  THEN 'Tablet'
WHEN LOWER(ITEM) LIKE '%phone%' THEN 'Phone'
END AS FORMATTED_ITEM
FROM MESSY_SALES_DATASET;

-- 3 STANDARDIZE PAYMENT_MEATHOD

SELECT `PAYMENT METH0D` ,
CASE 
WHEN `PAYMENT METH0D` IS NULL OR TRIM(`PAYMENT METH0D`) = '' THEN 'Unknown'
WHEN LOWER(`PAYMENT METH0D`) LIKE '%cash%' THEN 'Cash'
When LOWER(`PAYMENT METH0D`) LIKE '%credit card%' THEN 'Credit Card'
WHEN LOWER(`PAYMENT METH0D`) LIKE '%ewallet%' THEN 'E-Wallet'
when LOWER(`PAYMENT METH0D`) LIKE '%e-wallet%' THEN 'E-Wallet'
END AS PAYMENT_METHOD
FROM MESSY_SALES_DATASET;

-- 4  STANDARDIZE CUSTOMER_FEEDBACK

SELECT FEEDBACK ,
CASE
WHEN LOWER(FEEDBACK) LIKE '%poor%' THEN 'Poor'
WHEN LOWER(FEEDBACK) LIKE '%excellent%' THEN 'Excellent'
WHEN LOWER(FEEDBACK) LIKE '%bad%' THEN 'Bad'
ELSE 'Average'
END AS CUSTOMER_FEEDBACK
FROM MESSY_SALES_DATASET;


-- 5 STANDARDIZE QUANTITY

SELECT * ,
CASE
WHEN LOWER(QUANTITY) = 'two' THEN 2
WHEN LOWER(QUANTITY) = 'three' THEN 3
ELSE CAST(QUANTITY AS SIGNED)
END AS FORMATED_QUANTITY 
FROM MESSY_SALES_DATASET;

-- 5 STANDARDIZE CUSTOMER_NAME

SELECT `CUSTOMER NAME`,
CONCAT(UPPER(LEFT(`CUSTOMER NAME` , 1)),LOWER(SUBSTRING(`CUSTOMER NAME` ,2)))AS Formatted_name
FROM MESSY_SALES_DATASET;

-- 7 REMOVE DUPLICATE 

SELECT * 
FROM (
SELECT * ,
ROW_NUMBER() OVER (PARTITION BY ID ,`CUSTOMER NAME`, DATE_PURCHASED, ITEM ORDER BY DATE_PURCHASED)
AS
RN
FROM MESSY_SALES_DATASET
)AS SUB
WHERE RN = 1;


-----------------------------------------------------------------------------------------------
-- FILTERING CLEANED DATA (USING C.T.E)
-----------------------------------------------------------------------------------------------
-- USING C.T.E AND ROW_NUMBER() TO FILTER THE CLEANED DATA

WITH CLEANED_DATA AS(                                
SELECT ID AS CUSTOMER_ID,                                
       DATE_PURCHASED AS PURCHASED_DATE ,
	   `PR!CE` AS PRICE ,
       TOTALAMOUNT AS TOTAL_AMOUNT,
     
       
 `CUSTOMER NAME`,
CONCAT(UPPER(LEFT(`CUSTOMER NAME` , 1)),LOWER(SUBSTRING(`CUSTOMER NAME` ,2)))AS CUSTOMER_NAME,


 CITY ,
CASE
WHEN LOWER(CITY) LIKE '%new york%' THEN 'New York'
WHEN LOWER(CITY) LIKE '%los angeles%' THEN 'Los Angeles'
WHEN LOWER(CITY) LIKE '%chicago%' THEN 'Chicago'
ELSE 'Other'
END AS FORMATTED_CITY ,

 ITEM ,
CASE 
WHEN  LOWER(ITEM) LIKE '%laptop%' THEN 'Laptop'
WHEN LOWER(ITEM) LIKE '%tablet%'  THEN 'Tablet'
WHEN LOWER(ITEM) LIKE '%phone%' THEN 'Phone'
END AS FORMATTED_ITEM ,

 `PAYMENT METH0D` ,
CASE 
WHEN `PAYMENT METH0D` IS NULL OR TRIM(`PAYMENT METH0D`) = '' THEN 'Unknown'
WHEN LOWER(`PAYMENT METH0D`) LIKE '%cash%' THEN 'Cash'
When LOWER(`PAYMENT METH0D`) LIKE '%credit card%' THEN 'Credit Card'
WHEN LOWER(`PAYMENT METH0D`) LIKE '%ewallet%' THEN 'E-Wallet'
when LOWER(`PAYMENT METH0D`) LIKE '%e-wallet%' THEN 'E-Wallet'
END AS PAYMENT_METHOD,

 FEEDBACK ,
CASE
WHEN LOWER(FEEDBACK) LIKE '%poor%' THEN 'Poor'
WHEN LOWER(FEEDBACK) LIKE '%excellent%' THEN 'Excellent'
WHEN LOWER(FEEDBACK) LIKE '%bad%' THEN 'Bad'
ELSE 'Average'
END AS CUSTOMER_FEEDBACK ,


QUANTITY ,
CASE
WHEN LOWER(QUANTITY) = 'two' THEN 2
WHEN LOWER(QUANTITY) = 'three' THEN 3
ELSE CAST(QUANTITY AS SIGNED)
END AS FORMATTED_QUANTITY 

FROM MESSY_SALES_DATASET)


SELECT CUSTOMER_ID , CUSTOMER_NAME,  PURCHASED_DATE , PRICE , TOTAL_AMOUNT , CUSTOMER_FEEDBACK, 
 FORMATTED_CITY AS CITY  , FORMATTED_ITEM AS ITEM   , PAYMENT_METHOD , FORMATTED_QUANTITY AS QUANTITY
FROM(
SELECT * ,
ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ,`CUSTOMER NAME`, PURCHASED_DATE, ITEM ORDER BY PURCHASED_DATE)
AS
RN
FROM CLEANED_DATA
) AS CTE
WHERE RN = 1;

-----------------------------------------------------------------------------------------------
-- CREATING FINAL TABLE
-----------------------------------------------------------------------------------------------
-- CREATED A NEW TABLE WITH CLEAN DATA 

CREATE TABLE NEW_SALES_DATASET AS
WITH CLEANED_DATA AS (
  SELECT 
    ID AS CUSTOMER_ID,
    STR_TO_DATE(DATE_PURCHASED, '%Y-%m-%d') AS PURCHASED_DATE,
    `PR!CE` AS PRICE,
    TOTALAMOUNT AS TOTAL_AMOUNT,
    
    `CUSTOMER NAME`,
    CONCAT(UPPER(LEFT(`CUSTOMER NAME`, 1)), LOWER(SUBSTRING(`CUSTOMER NAME`, 2))) AS CUSTOMER_NAME,
    
    CITY,
    CASE
      WHEN LOWER(CITY) LIKE '%new york%' THEN 'New York'
      WHEN LOWER(CITY) LIKE '%los angeles%' THEN 'Los Angeles'
      WHEN LOWER(CITY) LIKE '%chicago%' THEN 'Chicago'
      ELSE 'Other'
    END AS FORMATTED_CITY,
    
    ITEM,
    CASE
      WHEN LOWER(ITEM) LIKE '%laptop%' THEN 'Laptop'
      WHEN LOWER(ITEM) LIKE '%tablet%' THEN 'Tablet'
      WHEN LOWER(ITEM) LIKE '%phone%' THEN 'Phone'
      ELSE 'OTHER'
    END AS FORMATTED_ITEM,
    
    `PAYMENT METH0D`,
    CASE
      WHEN `PAYMENT METH0D` IS NULL OR TRIM(`PAYMENT METH0D`) = '' THEN 'Unknown'
      WHEN LOWER(`PAYMENT METH0D`) LIKE '%cash%' THEN 'Cash'
      WHEN LOWER(`PAYMENT METH0D`) LIKE '%credit card%' THEN 'Credit Card'
      WHEN LOWER(`PAYMENT METH0D`) LIKE '%ewallet%' THEN 'E-Wallet'
      WHEN LOWER(`PAYMENT METH0D`) LIKE '%e-wallet%' THEN 'E-Wallet'
      ELSE 'Other'
    END AS PAYMENT_METHOD,
    
    FEEDBACK,
    CASE
      WHEN LOWER(FEEDBACK) LIKE '%poor%' THEN 'Poor'
      WHEN LOWER(FEEDBACK) LIKE '%excellent%' THEN 'Excellent'
      WHEN LOWER(FEEDBACK) LIKE '%bad%' THEN 'Bad'
      ELSE 'Average'
    END AS CUSTOMER_FEEDBACK,
    
    QUANTITY,
    CASE
      WHEN LOWER(QUANTITY) = 'two' THEN 2
      WHEN LOWER(QUANTITY) = 'three' THEN 3
      WHEN QUANTITY REGEXP '^[0-9]+$' THEN CAST(QUANTITY AS SIGNED)
      ELSE NULL
    END AS FORMATTED_QUANTITY
    
  FROM MESSY_SALES_DATASET
)
SELECT 
  CUSTOMER_ID,
  CUSTOMER_NAME,
  PURCHASED_DATE,
  PRICE,
  TOTAL_AMOUNT,
  CUSTOMER_FEEDBACK,
  FORMATTED_CITY AS CITY,
  FORMATTED_ITEM AS ITEM,
  PAYMENT_METHOD,
  FORMATTED_QUANTITY AS QUANTITY
FROM (
  SELECT *,
    ROW_NUMBER() OVER (
      PARTITION BY CUSTOMER_ID, `CUSTOMER NAME`, PURCHASED_DATE, ITEM 
      ORDER BY PURCHASED_DATE
    ) AS RN
  FROM CLEANED_DATA
) AS CTE
WHERE RN = 1;

SELECT * FROM NEW_SALES_DATASET;
